# Generated by Django 6.0.3 on 2026-03-23 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lenguaje', models.CharField(max_length=100)),
                ('es_ingles_tecnico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiscusionForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('es_duda_tecnica', models.BooleanField(default=False)),
                ('votos', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ejercicio', models.CharField(choices=[('C', 'Código'), ('Q', 'Quiz')], max_length=1)),
                ('enunciado', models.TextField()),
                ('xp_recompensa', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('tipo_usuario', models.CharField(choices=[('E', 'Estudiante'), ('R', 'Reclutador')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LigaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=50)),
                ('fecha_cierre', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizIngles',
            fields=[
                ('ejercicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aprendizaje.ejercicio')),
                ('url_audio', models.URLField(blank=True, max_length=500, null=True)),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RetoCodigo',
            fields=[
                ('ejercicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aprendizaje.ejercicio')),
                ('codigo_base', models.TextField()),
                ('casos_prueba', models.JSONField()),
                ('tiempo_limite', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aprendizaje.usuario')),
                ('racha_dias', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('xp_total', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Reclutador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aprendizaje.usuario')),
                ('empresa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.curso')),
            ],
            options={
                'unique_together': {('curso', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.leccion'),
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('votos', models.IntegerField(default=0)),
                ('discusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='aprendizaje.discusionforo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='discusionforo',
            name='solucion_respuesta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discusion_solucionada', to='aprendizaje.respuestaforo'),
        ),
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('url_github', models.URLField(blank=True, max_length=500, null=True)),
                ('url_linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('disponible', models.BooleanField(default=False)),
                ('habilidades', models.JSONField(blank=True, null=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='discusionforo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.estudiante'),
        ),
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('rango_salarial', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('reclutador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.reclutador')),
            ],
        ),
        migrations.CreateModel(
            name='RankingSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('xp_ganada_esta_semana', models.PositiveIntegerField(default=0)),
                ('puesto_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.ligasemanal')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'semana_inicio')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_completado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nivel_alcanzado', models.PositiveIntegerField(default=0)),
                ('ultimo_acceso', models.DateField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Enviada', 'Enviada'), ('En Revisión', 'En Revisión'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Enviada', max_length=30)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.ofertalaboral')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'oferta')},
            },
        ),
    ]
