# Generated by Django 6.0.3 on 2026-03-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0004_alter_reclutador_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_ultima_leccion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
