# Generated by Django 6.0.5 on 2026-05-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0005_estudiante_fecha_ultima_leccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
