# Generated by Django 6.0.5 on 2026-05-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0006_delete_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(blank=True, default='avatares/default_owl.png', null=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='vidas',
            field=models.IntegerField(default=5),
        ),
    ]
