# Generated by Django 6.0.5 on 2026-05-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0007_estudiante_avatar_estudiante_vidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='escuela',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
