# Generated by Django 6.0.5 on 2026-05-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0009_amistad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='vidas',
            new_name='energia',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='racha_ejercicios',
            field=models.IntegerField(default=0),
        ),
    ]
