# Generated by Django 6.0.5 on 2026-05-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0010_rename_vidas_estudiante_energia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_ultima_recarga',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
