# Generated by Django 6.0.5 on 2026-05-17 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0011_estudiante_fecha_ultima_recarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_ultima_recarga',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
