# Generated by Django 6.0.5 on 2026-05-18 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0013_pregunta_opcionrespuesta_quiz_pregunta_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetoInteractivo',
            fields=[
                ('ejercicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aprendizaje.ejercicio')),
                ('tipo_reto', models.CharField(choices=[('OM', 'Opción Múltiple'), ('RH', 'Rellenar Huecos (Tecleo)'), ('OT', 'Ordenar Texto (Drag & Drop)'), ('EP', 'Enlazar Palabras (Match)')], default='OM', max_length=2)),
                ('configuracion', models.JSONField(help_text='Estructura del reto (opciones, respuestas, pares, etc.)')),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='leccion',
        ),
        migrations.RemoveField(
            model_name='quizingles',
            name='ejercicio',
        ),
        migrations.DeleteModel(
            name='OpcionRespuesta',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizIngles',
        ),
    ]
