# Generated by Django 6.0.5 on 2026-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0014_retointeractivo_remove_pregunta_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='requisitos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
