# Generated by Django 6.0.5 on 2026-05-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0016_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título de la Novedad')),
                ('contenido', models.TextField(verbose_name='Contenido / Cuerpo del mensaje')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en el sistema?')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
