# Generated by Django 6.0.5 on 2026-05-20 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0017_novedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('xp', 'Recolectar XP'), ('lecciones', 'Completar Lecciones'), ('racha', 'Mantener Conexión (Racha)')], max_length=20)),
                ('meta', models.IntegerField(help_text='Cantidad a alcanzar (Ej: 50 para XP, 2 para lecciones)')),
                ('xp_recompensa', models.IntegerField(help_text='XP extra al completar el desafío')),
                ('icono', models.CharField(default='⚡', max_length=10)),
                ('color_barra', models.CharField(default='bar-gold', help_text='Clase CSS: bar-gold, bar-red, bar-blue', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('progreso_actual', models.IntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('recompensa_reclamada', models.BooleanField(default=False)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.desafiodiario')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_diarios', to='aprendizaje.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'desafio', 'fecha')},
            },
        ),
    ]
