# Generated by Django 6.0.5 on 2026-05-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0018_desafiodiario_progresodesafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclutador',
            name='contacto',
            field=models.CharField(blank=True, help_text='Correo electrónico o URL de LinkedIn', max_length=200, null=True),
        ),
    ]
