# Generated by Django 6.0.5 on 2026-05-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0019_alter_amistad_id_alter_curso_id_and_more'),
        ('aprendizaje', '0019_reclutador_contacto'),
    ]

    operations = [
    ]
