# Generated by Django 6.0.5 on 2026-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0021_remove_leccion_completada_alter_amistad_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertalaboral',
            name='requisitos',
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='requisitos_extras',
            field=models.TextField(blank=True, help_text='Habilidades deseables que suman puntos (Ej. Docker, SQL).', null=True),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='requisitos_obligatorios',
            field=models.TextField(blank=True, help_text='Máximo 2 o 3 habilidades clave (Ej. Python, Django).', null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='energia',
            field=models.IntegerField(default=10),
        ),
    ]
