# Generated by Django 6.0.5 on 2026-05-27 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0022_remove_ofertalaboral_requisitos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='protectores_racha',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CofreAbierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofres_abiertos', to='aprendizaje.estudiante')),
                ('leccion_previa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.leccion')),
            ],
            options={
                'unique_together': {('estudiante', 'leccion_previa')},
            },
        ),
    ]
